### ISSUE TITLE
bad import of gaussian_latitudes

### ISSUE THREAD

**Issue by alcoat** [NOAA-MDL/grib2io#121]
https://github.com/NOAA-MDL/grib2io/blob/6acd48cb71bcfa65c7ebd29fffd541ffbcb92773/grib2io/_grib2io.py#L965C35-L965C35

The line should be:
 from .utils.gauss_grid import gaussian_latitudes

**Comment by EricEngle-NOAA** [comment]
Thank you for report this.  This fix will be available in the next couple of days in v2.1.2 release.
