### ISSUE TITLE
Bad gridlengthXDirection when reading gaussian grid

### ISSUE THREAD

**Issue by alcoat** [NOAA-MDL/grib2io#123]
Input files could be CSFR V2 or any CFS forecast or may be any files with a gaussian grid
```python
import grib2io
file = "flxf2024011700.01.2024011700.grb2"
g = grib2io.open(file)
msg = g.select(shortName='UGRD')[0]
print(msg.gridlengthXDirection)
```
- Problem description: the result is 938.0 !
- Expected output : 0.938
- Plateform: Linux / conda
- Versions:
  * `Python 3.11.7`
  * `grib2io 2.1.2`

This issue is leading to an error in the xarray backend as the dimension of longitude is not correct using the msg.grid() method.

**Comment by EricEngle-NOAA** [comment]
Thanks for reporting.  I can confirm the issue.  I have identified the issue and a solution is working.  This also led me to discover a missing attribute for messages with Gaussian grids and is a fairly important one, the number of parallels.

v2.1.3 coming in the next few hours with this fix.

**Comment by EricEngle-NOAA** [comment]
v2.1.3 released with the fix for this.  It is now available on PyPI and will be available on conda-forge in a few hours.
