### ISSUE TITLE
Problem in bitmap test ?

### ISSUE THREAD

**Issue by alcoat** [NOAA-MDL/grib2io#144]
https://github.com/NOAA-MDL/grib2io/blob/f1643e3a84bc8d740481fd72ccef9a440c64220a/src/grib2io/_grib2io.py#L922
Shouldn't this line check that bitmap attribute is None ?
The bitmap attribute may always exists as it is set to None in the __post_init__ function
https://github.com/NOAA-MDL/grib2io/blob/f1643e3a84bc8d740481fd72ccef9a440c64220a/src/grib2io/_grib2io.py#L716

**Comment by alcoat** [comment]
The fix remove the bitmap attribute assignment and delete it when flush is called if it has been assigned

**Comment by EricEngle-NOAA** [comment]
Thanks for reporting.  It is the desire to always have `bitmap` attribute to exist.  It was an oversight to still use `hasattr()` for the bitmap.

**Comment by alcoat** [comment]
The file has been changed since my first patch : now, the line to change is : https://github.com/NOAA-MDL/grib2io/blob/master/src/grib2io/_grib2io.py#L928 with a check to None of the bitmap attribute.
