### ISSUE TITLE
Test suite improvements

### ISSUE THREAD

**Issue by jasonwashburn** [NOAA-MDL/grib2io#20]
Wondering if you'd be open to improving the test suite. I'm interested in developing an automated test suite with unit and integration tests, likely using Nox and Pytest; one that could be easily incorporated into both local development workflows and a build pipeline.

**Comment by eengl** [comment]
That sounds good to me!

**Comment by EricEngle-NOAA** [comment]
Closing this.  We have implemented tests in grib2io and [grib2io-interp](https://github.com/NOAA-MDL/grib2io-interp) using pytest.
