### ISSUE TITLE
How to clip a grib2 file based on lons and lats?

### ISSUE THREAD

**Issue by gc13141112** [NOAA-MDL/grib2io#22]
Include a clear description and an example or even a scholarly source of information about how the calculation, plot, etc. works

**Comment by eengl** [comment]
Most likely will implement a new Grib2Message method where you can "clip" the grid based on grid point and lat/lon bounds.    Another question to be asked here is if the method should return a new object **_or_** operate on the message object itself.

**Comment by EricEngle-NOAA** [comment]
Ideas for implementation:

Method for the Grib2Message object, `subgrid(latlons=None, xy=None)`

**Comment by EricEngle-NOAA** [comment]
Fulfilled
