### ISSUE TITLE
'kwargs' is not defined

### ISSUE THREAD

**Issue by huangynj** [NOAA-MDL/grib2io#27]
https://github.com/eengl/grib2io/blob/695be0edf65a4bc116f84cd4fb6af2da5874593b/grib2io/_grib2io.py#L1557

**Comment by eengl** [comment]
Thanks for catching this.  Fixing soon.

**Comment by eengl** [comment]
Fixed with c3bc9d4da736956adfd2598514c5c25bd5fcf090
