### ISSUE TITLE
Add support for product definition template 4.48

### ISSUE THREAD

**Issue by BenjaminBlake-NOAA** [NOAA-MDL/grib2io#49]
When trying to create plots of near-surface (8 m AGL) smoke/dust from a grib2 file, I get the following error message:

ValueError: Unsupported Product Definition Template Number - 4.48

Would it be possible to add support for this product definition template to grib2io?

**Comment by EricEngle-NOAA** [comment]
Support for PDTN = 48 has been added.  Closing this issue.
