### ISSUE TITLE
Seek bugfix reverted

### ISSUE THREAD

**Issue by zflamig** [NOAA-MDL/grib2io#50]
Looks like the bugfix to seek was reverted in the xarray PR: https://github.com/NOAA-MDL/grib2io/blob/master/grib2io/_grib2io.py#L418

**Comment by EricEngle-NOAA** [comment]
Thanks for reporting!  Are you having issues when performing `seek(1)`?

**Comment by zflamig** [comment]
Correct. Seek(1) crashes

**Comment by EricEngle-NOAA** [comment]
@zflamig OK with you to close this?
