### ISSUE TITLE
Distribution through conda

### ISSUE THREAD

**Issue by wxguy** [NOAA-MDL/grib2io#53]
When will this library be added to `onda-forge` ecosystem?

**Comment by EricEngle-NOAA** [comment]
We planning and hope to have `grib2io` available on `conda-forge` for its v2.0 release.

**Comment by wxguy** [comment]
Thank you for your response. Any timeline fixed?

**Comment by EricEngle-NOAA** [comment]
grib2io v2.0.0 is dependent on 3 external libraries provided by NCEP.  These are g2c, sp, and ip.  g2c and sp have already been submitted to conda-forge.  ip will follow once it has an updated release...then grib2io v2.0.0

**Comment by EricEngle-NOAA** [comment]
**UDPATE** on this...

* grib2io v2.0 will be release by Fri, 7/7/2023 and will be on PyPI and conda-forge
* grib2io-interp is the interpolation component for grib2io v2.0+. It currently available on conda-forge via
```shell
conda install -c conda-forge grib2io-interp
```
* The 3 supporting NCEP libraries are available on conda-forge
```shell
conda install -c conda-forge nceplibs-g2c nceplibs-sp nceplibs-ip
```

**Comment by EricEngle-NOAA** [comment]
grib2io v2.0.0 will be release on Monday, July 10 and should be on conda-forge within the day

**Comment by wxguy** [comment]
Waiting for the release. Please update your user documentation for us to test and report back issues.
