### ISSUE TITLE
pip install fail

### ISSUE THREAD

**Issue by marstonsward** [NOAA-MDL/grib2io#65]
```python
#  grib2io-1.1.0.tar.gz
 pip install grib2io
```
-  g2clib.c:745:10: fatal error: grib2.h: No such file or directory
        745 | #include "grib2.h"
- Linux
- Versions: 
  * python  3.11.1
  * cfgrib  0.9.10.3
  * eccodes 2.29.0

**Comment by EricEngle-NOAA** [comment]
HI @Marston.  grib2io does not interface with eccodes/cfgrib, so those are not required for grib2io.  grib2io interfaces with the NCEPLIBS-g2c library.  So that must be installed prior to installing grib2io.

See the procedure for g2c build and install here: https://github.com/NOAA-EMC/NCEPLIBS-g2c#building

**Comment by EricEngle-NOAA** [comment]
That is because prior to grib2io v1.1.0, g2c library was bundled in the source code.  v1.1.0 removed this and pointed to an existing installation of g2c.  See [v1.1.0 release notes](https://github.com/NOAA-MDL/grib2io/releases/tag/v1.1.0)

**Comment by Marston** [comment]
Got NCEPLIBS installed and will install grib2io manually. Thanks for the help.

**Comment by Marston** [comment]
@EricEngle-NOAA 

I'm able to install the NCEPLIB-g2c/sp/ip into a conda/mamba environment.

```
#!/bin/bash
set -e

source $HOME/mambaforge-pypy3/etc/profile.d/conda.sh
conda activate grib

echo 'Install NCEPLIB-g2c'
rm -rf NCEP* ncep*
wget -O nceplibs-g2c-1.7.0 https://github.com/NOAA-EMC/NCEPLIBS-g2c/archive/refs/tags/v1.7.0.tar.gz
tar xvf nceplibs-g2c-1.7.0
cd NCEPLIBS-g2c-1.7.0
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_PREFIX_PATH=$CONDA_PREFIX ..
make -j8
make test
make install
```

This works but I can only get version 1.1.0 installed: `pip install grib2io==1.1.0` not the latest release. You have hardcoded some paths to ip and that causes the build to fail. Created an issue.
