### ISSUE TITLE
Writing GRIB2 Messages Examples

### ISSUE THREAD

**Issue by cjmelick** [NOAA-MDL/grib2io#73]
Greetings,

I have utilized the __init__(), addgrid(), and addfield() methods to create a new GRIB2 message with all of the constituent arguments required for each but it seems like my created message is not complete when trying to do some testing with decoding and was curious if there is a location which shows examples of generating GRIB2 products/data from scratch?

Thanks,
Chris

**Comment by EricEngle-NOAA** [comment]
Hi Chris,

The methods you listed are a part of the grib2io v1.x API where init() creates the message (sections 0 and 1), addgrid() adds section 3, and addfield() adds sections 4, 5, 6, 7.  There is 1 more method to formally end the grid message, `end()`, which adds section 8 (a string of `'7777'`).  Note that the workflow for creating new GRIB2 message in v2.x will have changed significantly.

**Comment by cjmelick** [comment]
Hi Eric,

I did just add in the end() method but it seems like that all parts of the message are not filled out and so I have problems accessing the data array I just created.   Also, I get no errors when setting up all of the methods for the new GRIB2 message.   Has this issue been seen before?

Thanks,
Chris

**Comment by EricEngle-NOAA** [comment]
Feel free to share your code here.  It is possible there was an issue in addgrid or addfield that didnt make it back to you.

**Comment by cjmelick** [comment]
Eric, here is my code.   I was just trying to build up from scratch an existing GRIB2 message from the GFS model.   Thanks for your assistance!
#!/usr/bin/env python3
import grib2io
import sys
import numpy as np
import re
// gfsfile --> 24-hour forecast GFS 0.5deg gridded data file in GRIB2 format
obj=grib2io.open(gfsfile)
msg = obj[1][0]
dat = msg.data()
//fullName = Pressure Reduced to MSL for msg #1
newmsg = grib2io.Grib2Message
newmsg.init(newmsg,discipline=msg.discipline.value,idsect=msg.identificationSection)
newmsg.addgrid(newmsg,msg.gridDefinitionSection,msg.gridDefinitionTemplate)
newmsg.addfield(newmsg,dat,msg.productDefinitionTemplateNumber,msg.productDefinitionTemplate,packing='simple', binScaleFactor = msg.binScaleFactor, decScaleFactor = msg.decScaleFactor)
newmsg.end(newmsg)
print(newmsg)
print(newmsg.data(newmsg))

**Comment by cjmelick** [comment]
Hi Eric,

I had success with what you provided as a solution!  This issue can be closed.  

Thanks again!
Chris
