### ISSUE TITLE
User documentation for the project

### ISSUE THREAD

**Issue by wxguy** [NOAA-MDL/grib2io#91]
The official website for documentation of this project is https://noaa-mdl.github.io/grib2io. But the link is all about developer documentation. In addition, there is not even a single example given there. 

Therefore, I propose to have user documentation for this package (similar to what pygrib or wrf-python have) and the dev documentation may be kept at the end of it. Ideally the user documentation should have a few sample data sets and example scripts (even with comments are fine) for some use cases.

**Comment by EricEngle-NOAA** [comment]
Thank you for this.  We will work to make this better.  In the meantime, there is a notebook in the project repo that demonstrates version 2.0 usage: https://github.com/NOAA-MDL/grib2io/blob/master/grib2io-v2-demo.ipynb

**Comment by wxguy** [comment]
> Thank you for this. We will work to make this better. In the meantime, there is a notebook in the project repo that demonstrates version 2.0 usage: https://github.com/NOAA-MDL/grib2io/blob/master/grib2io-v2-demo.ipynb

Perfect. This should have been in the introduction section of official documentation.

Thank you.
