### ISSUE TITLE
Fix setup.py to properly find g2c include directory when using G2C_DIR

### ISSUE THREAD

**Issue by EricEngle-NOAA** [NOAA-MDL/grib2io#93]
The setup.py fails to define g2c_incdir when g2c is defined by env var `G2C_DIR`.

**Comment by lboeman** [comment]
Hello, while trying to install v2.0.0 I ran into this problem and  looks like It it is fixed on master with commit: https://github.com/NOAA-MDL/grib2io/commit/8db08fa15babb957a0df90ab5c9d046a07e9262b .

**Comment by EricEngle-NOAA** [comment]
Yes.  Apologies for this...its one of those small bugs that I thought I had ironed out in all scenarios.

**Comment by EricEngle-NOAA** [comment]
Fixed in v2.0.1
