### ISSUE TITLE
Installing grib2io with conda is not working

### ISSUE THREAD

**Issue by isabelSTst** [NOAA-MDL/grib2io#94]
Hello, I have been trying to install grib2io for the past few days on an anaconda environment using the command: conda install -c conda-forge grib2io on the terminal but it doesn't work. It always gets stuck here (for several hours):

Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: /

I first installed it on the anaconda base and I haven't had any problems but I'm stuck here when I try to install it on a specific environment.
I don't know what it is happening or why it is not working but I need this library to work with grib2 files.

**Comment by EricEngle-NOAA** [comment]
Hello.  Have you tried cleaning up the conda environment?

https://docs.conda.io/projects/conda/en/latest/commands/clean.html

**Comment by EricEngle-NOAA** [comment]
Hi.  Have you had any success?

**Comment by EricEngle-NOAA** [comment]
Closing this for now.  Please comment here again if need to re-open.
